export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const RESET_CREATED_FLAG = 'RESET_CREATED_FLAG';
export const RESET_ERROR = 'RESET_ERROR';